"""initial tables

Revision ID: 51c4e700b8f9
Revises: 
Create Date: 2023-05-23 23:38:27.083767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c4e700b8f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits_raw',
        sa.Column('cast', sa.VARCHAR(), nullable=True),
        sa.Column('crew', sa.VARCHAR(), nullable=True),
        sa.Column('id', sa.DECIMAL(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords_raw',
        sa.Column('id', sa.DECIMAL(), autoincrement=False, nullable=False),
        sa.Column('keywords', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links_raw',
        sa.Column('movie_id', sa.DECIMAL(), autoincrement=False, nullable=False),
        sa.Column('imdb_id', sa.VARCHAR(), nullable=True),
        sa.Column('tmdb_id', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('movie_id')
    )
    op.create_table('movie_metadata_raw',
        sa.Column('adult', sa.VARCHAR(), nullable=True),
        sa.Column('belongs_to_collection', sa.VARCHAR(), nullable=True),
        sa.Column('budget', sa.VARCHAR(), nullable=True),
        sa.Column('genres', sa.VARCHAR(), nullable=True),
        sa.Column('homepage', sa.VARCHAR(), nullable=True),
        sa.Column('id', sa.DECIMAL(), autoincrement=False, nullable=False),
        sa.Column('imdb_id', sa.VARCHAR(), nullable=True),
        sa.Column('original_language', sa.VARCHAR(), nullable=True),
        sa.Column('original_title', sa.VARCHAR(), nullable=True),
        sa.Column('overview', sa.VARCHAR(), nullable=True),
        sa.Column('popularity', sa.VARCHAR(), nullable=True),
        sa.Column('poster_path', sa.VARCHAR(), nullable=True),
        sa.Column('production_companies', sa.VARCHAR(), nullable=True),
        sa.Column('production_countries', sa.VARCHAR(), nullable=True),
        sa.Column('release_date', sa.VARCHAR(), nullable=True),
        sa.Column('revenue', sa.VARCHAR(), nullable=True),
        sa.Column('runtime', sa.VARCHAR(), nullable=True),
        sa.Column('spoken_languages', sa.VARCHAR(), nullable=True),
        sa.Column('status', sa.VARCHAR(), nullable=True),
        sa.Column('tagline', sa.VARCHAR(), nullable=True),
        sa.Column('title', sa.VARCHAR(), nullable=True),
        sa.Column('video', sa.VARCHAR(), nullable=True),
        sa.Column('vote_average', sa.VARCHAR(), nullable=True),
        sa.Column('vote_count', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings_raw',
        sa.Column('user_id', sa.DECIMAL(), nullable=False),
        sa.Column('movie_id', sa.DECIMAL(), nullable=False),
        sa.Column('rating', sa.DECIMAL(), nullable=True),
        sa.Column('timestamp', sa.DECIMAL(), nullable=True),
        sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings_raw')
    op.drop_table('movie_metadata_raw')
    op.drop_table('links_raw')
    op.drop_table('keywords_raw')
    op.drop_table('credits_raw')
    # ### end Alembic commands ###
