
version: 2

models:
  - name: genres
    columns:
      - name: name
      - name: id

sources:
  - name: movies
    database: intro
    schema: intro
    tables:
      - name: movie_metadata_raw
        columns:
          - name: adult
          - name: belongs_to_collection
          - name: budget
          - name: genres
          - name: homepage
          - name: id
          - name: imdb_id
          - name: original_language
          - name: original_title
          - name: overview
          - name: popularity
          - name: poster_path
          - name: production_companies
          - name: production_countries
          - name: release_date
          - name: revenue
          - name: runtime
          - name: spoken_languages
          - name: status
          - name: tagline
          - name: title
          - name: video
          - name: vote_average
          - name: vote_count
      - name: credits_raw
        columns:
          - name: cast
          - name: crew
          - name: id
      - name: keywords_raw
        columns:
          - name: id
          - name: keywords
      - name: links_raw
        columns:
          - name: movie_id
          - name: imdb_id
          - name: tmdb_id
      - name: ratings_raw
        columns:
          - name: user_id
          - name: movie_id
          - name: rating
          - name: timestamp
