name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Prepare for deploy
        run: |
          cp -r ./dbt_intro ./dags/
          python populate_config.py --snowflake-account=${{ secrets.SNOWFLAKE_ACCOUNT }} --snowflake-user=${{ secrets.SNOWFLAKE_USER }} --snowflake-password=${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: Deploy website to AWS bucket
        run: |
          aws s3 ls s3://airflow-bucket.tanay.tech
          aws s3 sync ./airflow/dags/ s3://airflow-bucket.tanay.tech/dags --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
